service: fwr30-test-example
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: cn-north-1

functions:
  testtrigger:
    handler: index.handler
    name: testingTriggerInputs
    description: blahblahblah
    events:
      - iot:
          name: triggerEggs
          sql: "SELECT *, clientid() AS clientId, topic(3) AS serial_number, topic() AS iot_topic FROM 'mc/faggot/#'"
          enabled: true
          sqlVersion: '2016-03-23'
